{% set name = "jpterm" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a39a1e89305f51411f8c19a30a0bd8c40d38e1a41d41d5775fe16ca3377ac5aa

build:
  noarch: python
  number: 1
  entry_points:
    - jpterm = jpterm.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - rich-click >=1.6.0
    - txl =0.3.2
    - txl-cell =0.3.6
    - txl-console =0.3.6
    - txl-editors =0.3.6
    - txl-file-browser =0.3.6
    - txl-image-viewer =0.3.6
    - txl-jpterm =0.3.6
    - txl-kernel =0.3.8
    - txl-local-contents =0.3.6
    - txl-local-terminals =0.3.6
    - txl-local-kernels =0.3.6
    - txl-notebook-editor =0.3.6
    - txl-remote-contents =0.3.6
    - txl-remote-terminals =0.3.6
    - txl-remote-kernels =0.3.6
    - txl-text-editor =0.3.6
    - txl-markdown-viewer =0.3.6
    - txl-terminal =0.3.6
    - txl-launcher =0.3.6
    - txl-widgets =0.3.6

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - jpterm --help
  imports:
    - jpterm

about:
  home: https://github.com/davidbrochart/jpterm
  summary: Jupyter in the terminal
  dev_url: https://github.com/davidbrochart/jpterm
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
